name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Pre-config
        run: |
          git config --global user.email "git@snapp.market"
          git config --global user.name "snappmarket" 
          git remote add origin https://github.com/snappmarket/frontend-toolbox.git

      - name: Generate changeslog
        run: bash ./scripts/changeLog/index.sh -r 'github.com/snappmarket/frontend-toolbox.git' -b 'develop'
        env:
          CI_USER: ${{ secrets.CI_USER }}
          CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
